version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - /mnt/c/Users/User/_Media:/media
      - ./data/jellyfin/config:/config
      - ./data/jellyfin/cache:/cache

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
    networks:
      home_net:
        aliases:
          - jellyfin


networks:
  home_net:
    external: true




