version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "${JELLYFIN_PORT}:8096"
    volumes:
      - ./media/media
      - ./data/jellyfin/config:/config
      - ./data/jellyfin/cache:/cache
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
    networks:
      - homelab_net

networks:
  homelab_net:
    external: true




