version: '3.8'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - "${NEXTCLOUD_PORT}:80"
    volumes:
      - ./compose-files/data/nextcloud/html:/var/www/html
    environment:
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_ROOT}
    depends_on:
      - db
    networks:
      - home_net

  db:
    image: mariadb
    container_name: nextcloud-db
    restart: unless-stopped
    volumes:
      - ./compose-files/data/nextcloud/db:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${NEXTCLOUD_DB_ROOT}
      - MARIADB_DATABASE=nextcloud
      - MARIADB_USER=nextcloud
      - MARIADB_PASSWORD=${NEXTCLOUD_DB_PASS}

    networks:
      - home_net

networks:
  home_net:
    external: true
