services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "${PORTAINER_PORT}:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer/data:/data
    restart: unless-stopped
    networks:
      - homelab_net

networks:
  homelab_net:
    external: true