services:
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    ports:
      - "${TAUTULLI_PORT}:8181"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ./data/tautulli/config:/config
    restart: unless-stopped
    networks:
      - homelab_net

networks:
  homelab_net:
    external: true