services:
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    ports:
      - "8181:8181"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ./tautulli/config:/config
    restart: unless-stopped